In [2]:
import numpy as np
from mpl_toolkits import mplot3d
from mpl_toolkits.mplot3d import axes3d
import matplotlib.pyplot as plt
import random
from sympy import *
#plt.style.use('seaborn-poster')

In [38]:
from sympy import *
x = sym.Symbol('x')
y = sym.Symbol('y')
r = list([0,1,-1])
s = list([10,4,-1])
px, py = 1, 1
for i in range(3):
    px = px * (x-r[i])
    py = py * (y-s[i])

g = 12*integrate(px, x) + 12*integrate(py, y)

for i in r:
    for j in s:
        print(i,j,'\t',g.subs([(x,i),(y,j)]),'\t', diff(diff(g,x),x).subs([(x,i),(y,j)]), '\t', diff(diff(g,y),y).subs([(x,i),(y,j)]))
print()
for i in r:
    for j in s:
        print(i,j,'\t', diff(g,x).subs([(x,i),(y,j)]), '\t', diff(g,y).subs([(x,i),(y,j)]))
print()
for i in r:
    for j in s:
        print(i,j,'\t', diff(diff(g,x),x).subs([(x,i),(y,j)]), '\t', diff(diff(g,y),y).subs([(x,i),(y,j)]))

0 10 	 -1600 	 -12 	 792
0 4 	 1856 	 -12 	 -360
0 -1 	 -269 	 -12 	 660
1 10 	 -1603 	 24 	 792
1 4 	 1853 	 24 	 -360
1 -1 	 -272 	 24 	 660
-1 10 	 -1603 	 24 	 792
-1 4 	 1853 	 24 	 -360
-1 -1 	 -272 	 24 	 660

0 10 	 0 	 0
0 4 	 0 	 0
0 -1 	 0 	 0
1 10 	 0 	 0
1 4 	 0 	 0
1 -1 	 0 	 0
-1 10 	 0 	 0
-1 4 	 0 	 0
-1 -1 	 0 	 0

0 10 	 -12 	 792
0 4 	 -12 	 -360
0 -1 	 -12 	 660
1 10 	 24 	 792
1 4 	 24 	 -360
1 -1 	 24 	 660
-1 10 	 24 	 792
-1 4 	 24 	 -360
-1 -1 	 24 	 660


In [83]:
from sympy import *
x = Symbol('x')
y = Symbol('y')
z = Symbol('z')
r = list([0,1,3])
s = list([0,1,3])
t = list([0,1,3])
px, py, pz = 1, 1, 1
for i in range(3):
    px = px * (x-r[i])
    py = py * (y-s[i])
    pz = pz * (z-t[i])
g = 12*integrate(px, x) + 24*integrate(py, y) + 36*integrate(pz, z)
#print(g)
vals = []
for i in r:
    for j in s:
        for k in t:
            dxx = diff(diff(g,x),x).subs([(x,i),(y,j),(z,k)])
            dyy = diff(diff(g,y),y).subs([(x,i),(y,j),(z,k)])
            dzz = diff(diff(g,z),z).subs([(x,i),(y,j),(z,k)])
            v = g.subs([(x,i),(y,j),(z,k)])
            if (dxx>=0 and dyy>=0 and dzz>=0):
                print(i,j,k,'\t',v,'\t', dxx, '\t', dyy, '\t', dzz)
                vals.append(v)
#             else:
#                 print()
#print()        
#print(len(vals))
#print(vals)
print(vals)
print(vals.count(min(vals)))

0 0 0 	 0 	 36 	 72 	 108
0 0 3 	 -81 	 36 	 72 	 216
0 3 0 	 -54 	 36 	 144 	 108
0 3 3 	 -135 	 36 	 144 	 216
3 0 0 	 -27 	 72 	 72 	 108
3 0 3 	 -108 	 72 	 72 	 216
3 3 0 	 -81 	 72 	 144 	 108
3 3 3 	 -162 	 72 	 144 	 216
[0, -81, -54, -135, -27, -108, -81, -162]
1


In [80]:
def pr(r,s,t):
    x = Symbol('x')
    y = Symbol('y')
    z = Symbol('z')
    px, py, pz = 1,1,1
    for i in range(3):
        px = px * (x-r[i])
        py = py * (y-s[i])
        pz = pz * (z-t[i])
    g = 12*integrate(px, x) + 12*integrate(py, y) + 12*integrate(pz, z)
    vals = []
    for i in r:
        for j in s:
            for k in t:
                dxx = diff(diff(g,x),x).subs([(x,i),(y,j),(z,k)])
                dyy = diff(diff(g,y),y).subs([(x,i),(y,j),(z,k)])
                dzz = diff(diff(g,z),z).subs([(x,i),(y,j),(z,k)])
                v = g.subs([(x,i),(y,j),(z,k)])
                #print(i,j,'\t',v,'\t', dxx, '\t', dyy, '\t', dzz, end="\t")
                if (dxx>=0 and dyy>=0 and dzz>=0):
                    #print("*")
                    vals.append(v)
    return(vals.count(min(vals)))

for i in range(100):
    r = np.random.randint(4, size=3)
    s = np.random.randint(10, size=3)
    t = np.random.randint(10, size=3)
    if(pr(r,2*r,3*r) <= 4 and distinct(r) and 0 in r and max(r)==2):
        print(np.sort(r))

In [79]:
def pr(r,s,t,u):
    x = Symbol('x')
    y = Symbol('y')
    z = Symbol('z')
    w = Symbol('w')
    px, py, pz, pw = 1,1,1,1
    for i in range(3):
        px = px * (x-r[i])
        py = py * (y-s[i])
        pz = pz * (z-t[i])
        pw = pw * (z-u[i])
    g = 12*integrate(px, x) + 12*integrate(py, y) + 12*integrate(pz, z) + 12*integrate(pw, w)
    vals = []
    for i in r:
        for j in s:
            for k in t:
                for l in u:
                    dxx = diff(diff(g,x),x).subs([(x,i),(y,j),(z,k),(w,l)])
                    dyy = diff(diff(g,y),y).subs([(x,i),(y,j),(z,k),(w,l)])
                    dzz = diff(diff(g,z),z).subs([(x,i),(y,j),(z,k),(w,l)])
                    dww = diff(diff(g,w),w).subs([(x,i),(y,j),(z,k),(w,l)])
                    v = g.subs([(x,i),(y,j),(z,k),(w,l)])
                    #print(i,j,'\t',v,'\t', dxx, '\t', dyy, '\t', dzz, end="\t")
                    if (dxx>=0 and dyy>=0 and dzz>=0 and dww>=0):
                        #print("*")
                        vals.append(v)
    if (len(vals)==0):
        return 100
    return(vals.count(min(vals)))

for i in range(100):
    r = np.random.randint(5, size=3)
    if(pr(r,2*r,3*r, 4*r) <= 4 and distinct(r) and 0 in r and max(r)==2):
        print(np.sort(r))

[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]
[0 1 2]


In [28]:
r = np.random.randint(10, size=3)
s = np.random.randint(10, size=3)
t = np.random.randint(10, size=3)
x = Symbol('x')
y = Symbol('y')
z = Symbol('z')
px, py, pz = 1, 1, 1
for i in range(3):
    px = px * (x-r[i])
    py = py * (y-s[i])
    pz = pz * (z-t[i])
g = 12*integrate(px, x) + 12*integrate(py, y) + 12*integrate(pz, z)
vals = []
for i in r:
    for j in s:
        for k in t:
            dxx = diff(diff(g,x),x).subs([(x,i),(y,j),(z,k)])
            dyy = diff(diff(g,y),y).subs([(x,i),(y,j),(z,k)])
            dzz = diff(diff(g,z),z).subs([(x,i),(y,j),(z,k)])
            v = g.subs([(x,i),(y,j),(z,k)])
            print(i,j,k,'\t',v,'\t', dxx, '\t', dyy, '\t', dzz, end="\t")
            if (dxx>=0 and dyy>=0 and dzz>=0):
                print("*")
                vals.append(v)
            else:
                print()
print(vals)
print(vals.count(max(vals)))

5 4 9 	 -2230 	 96 	 -36 	 72	
5 4 8 	 -2219 	 96 	 -36 	 -60	
5 4 3 	 -3094 	 96 	 -36 	 360	
5 5 9 	 -2237 	 96 	 48 	 72	*
5 5 8 	 -2226 	 96 	 48 	 -60	
5 5 3 	 -3101 	 96 	 48 	 360	*
5 1 9 	 -2365 	 96 	 144 	 72	*
5 1 8 	 -2354 	 96 	 144 	 -60	
5 1 3 	 -3229 	 96 	 144 	 360	*
3 4 9 	 -2182 	 -48 	 -36 	 72	
3 4 8 	 -2171 	 -48 	 -36 	 -60	
3 4 3 	 -3046 	 -48 	 -36 	 360	
3 5 9 	 -2189 	 -48 	 48 	 72	
3 5 8 	 -2178 	 -48 	 48 	 -60	
3 5 3 	 -3053 	 -48 	 48 	 360	
3 1 9 	 -2317 	 -48 	 144 	 72	
3 1 8 	 -2306 	 -48 	 144 	 -60	
3 1 3 	 -3181 	 -48 	 144 	 360	
1 4 9 	 -2230 	 96 	 -36 	 72	
1 4 8 	 -2219 	 96 	 -36 	 -60	
1 4 3 	 -3094 	 96 	 -36 	 360	
1 5 9 	 -2237 	 96 	 48 	 72	*
1 5 8 	 -2226 	 96 	 48 	 -60	
1 5 3 	 -3101 	 96 	 48 	 360	*
1 1 9 	 -2365 	 96 	 144 	 72	*
1 1 8 	 -2354 	 96 	 144 	 -60	
1 1 3 	 -3229 	 96 	 144 	 360	*
[-2237, -3101, -2365, -3229, -2237, -3101, -2365, -3229]
2


In [68]:
def distinct(r):
    l = len(r)
    for i in range(l):
        for j in range(i+1,l):
            if(r[i]==r[j]):
                return False
    return True

In [67]:
n = 5
x = symbols('x_0:{}'.format(n))
r = [0,1,3]
t = Symbol('t')
p = (t - r[0]) * (t - r[1]) * (t - r[2])
pols = [p for i in range(n)]
for i in range(n):
    #print(x[i])
    pols[i] = (x[i] - r[0]) * (x[i] - r[1]) * (x[i] - r[2])
poly = 0
for i in range(n):
    poly = poly + 12 * integrate(pols[i],x[i])
values = []
for i in range(2**n):
    b = [int(i) for i in str(bin(i)[2:])]
    l = len(b)
    b = 3*np.array(np.concatenate([[0]*(n-l+1), b]))[1:]
    substitute = [(x[i],b[i]) for i in range(n)]
    values.append(poly.subs(substitute))
print(values)
print(values.count(min(values)))
print(len(values))


[0, -27, -27, -54, -27, -54, -54, -81, -27, -54, -54, -81, -54, -81, -81, -108, -27, -54, -54, -81, -54, -81, -81, -108, -54, -81, -81, -108, -81, -108, -108, -135]
1
32


In [39]:
n=3
x = symbols('x_0:{}'.format(n))
for i in range(2**n):
    b = [int(i) for i in str(bin(i)[2:])]
    l = len(b)
    b = np.array(np.concatenate([[0]*(n-l+1), b]))[1:]
    substitute = [(x[i],b[i]*3) for i in range(n)]
    print(substitute)
    #print(b[1:])

[(x_0, 0), (x_1, 0), (x_2, 0)]
[(x_0, 0), (x_1, 0), (x_2, 3)]
[(x_0, 0), (x_1, 3), (x_2, 0)]
[(x_0, 0), (x_1, 3), (x_2, 3)]
[(x_0, 3), (x_1, 0), (x_2, 0)]
[(x_0, 3), (x_1, 0), (x_2, 3)]
[(x_0, 3), (x_1, 3), (x_2, 0)]
[(x_0, 3), (x_1, 3), (x_2, 3)]


In [3]:
t = Symbol('t')
(expand(integrate(12*t*(t-1)*(t-2),t)))

3*t**4 - 12*t**3 + 12*t**2